version: "3.9"

services:
  taskly-postgres:
    image: bitnami/postgresql:17.6.0-debian-12-r4
    container_name: taskly-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - taskly-postgres-data:/bitnami/postgresql
    ports:
      - "5432:5432"
    restart: unless-stopped

  taskly-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskly-app-go
    depends_on:
      - taskly-postgres
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  taskly-postgres-data:
